### PR TITLE
#213: updated documentation

### PR DESCRIPTION
**Pull request by mortenwh**
Issue #213. This contains updates to the docs in relation to https://github.com/metno/S-ENDA-csw-catalog-service/pull/8.

### CODE REVIEW

**Review by ElodieFZ — COMMENTED** [review]
It should be explicitely said that one must create the `lib/input_mmd_files` directory in the root folder of the repo  before adding the MMD test files.

**Comment by mortenwh** [comment]
> It should be explicitely said that one must create the `lib/input_mmd_files` directory in the root folder of the repo before adding the MMD test files.

This should be created when you provision the machine.. But maybe it's not for the localdev vm... I'll check.

**Comment by ElodieFZ** [comment]
The `lib` directory is created when you provision the machine, but not the `input_mmd_files` subdirectory.
Also provisioning the machine is described the second point after adding the mmd files, so maybe the order should be reversed? First provision the machine, and then add the mmd files?

**Comment by mortenwh** [comment]
yes - clearly :+1:

**Review by ElodieFZ — APPROVED** [review]

**Pull request merged**
