### PR TITLE
Issue219 nina metadata info

### PR DESCRIPTION
**Pull request by mdlux**
Draft of NINA metadata info. To be checked

### CODE REVIEW

**Comment by niellaNina** [comment]
Hi Matteo, I only had two comments to your text:
Description: could you add something short about the type of data you will have in the data portal ( for example add some words like biodiversity and anything else suitable)

And in Conditions and Requirements: could you change from MET to S-ENDA in line 65 and 66? the requirements are coming mostly from MET right now, but since it is supposed to be a shared project I think it is better to list the project rather than MET

**Comment by mdlux** [comment]
Ok, changes made

**Comment by mortenwh** [comment]
@niellaNina - will you look through and merge this?

**Review by niellaNina — APPROVED** [review]
Looks good now. good description of data

**Pull request merged**
